### PR TITLE
#112 review and suggestions guide/scaling-up/tooling #112

### PR DESCRIPTION
**Pull request by savionascimentodev**
solves #112

### CODE REVIEW

**Comment by viniciusdeliz** [comment]
A note on this: PR mentions issue #112 but there is a commit that makes changes to the file from issue #110. Ideally we would keep commits respective to its issues/branches/PRs.

**Comment by viniciusdeliz** [comment]
Great work by the way! I'll provide some more suggestions in a PR in your repo @savionascimentodev

**Comment by savionascimentodev** [comment]
Thanks, sir, I got it and adjusted!

**Review by nazarepiedady — APPROVED** [review]
It seems good to me, well done.

**Pull request merged**
