### PR TITLE
chore: add `vercel.json` to project root folder #128

### LINKED ISSUE #128: Hydration mismatch results in improper rendering
hydration-mismatch

That's also happening with some other pages atm

### PR DESCRIPTION
**Pull request by viniciusdeliz**
- Resolves #128 from docs-pt

- Issue [#2560](https://github.com/vuejs/docs/issues/2560) and [#2664](https://github.com/vuejs/docs/pull/2664) from vuejs/docs

### CODE REVIEW

**Review by Jinjiang — APPROVED** [review]

**Comment by Jinjiang** [comment]
@vuejs-translations/ar 
@vuejs-translations/cs 
@vuejs-translations/uk
Please have a look at this issue + PR which might solve the rendering issue on certain URLs in your translations. 🙏

**Comment by AloisSeckar** [comment]
I will certainly incorporate this into Czech version asap. I am just waiting to get maintainer privileges again to be able to set up ryu-cho to re-establish sync with upstream. Or should I copy the changes manually for now?

**Comment by Jinjiang** [comment]
@AloisSeckar I updated the permission settings. Please check again. Thanks.

**Comment by AloisSeckar** [comment]
@Jinjiang I confirm I can manage settings again, thank you.

**Comment by AloisSeckar** [comment]
@Jinjiang sorry for false possitive :( I haven't noticed in the morning, that although I have access to **some** settings, my options are limited and I still cannot manage repository secrets. 

I need to setup RYU_CHO_USER_NAME, RYU_CHO_USER_EMAIL and RYU_CHO_ACCESS_TOKEN to make syncing work. Or can you add them with some values used across the projects?

**Comment by Jinjiang** [comment]
@AloisSeckar sure. let's create another issue discussing this if you don't mind :-)

**Pull request merged**
